### ISSUE TITLE
npm start -s is not working on windows machines

### ISSUE THREAD

**Issue by sethhays** [philopian/AppSeed#1]
There is a problem with the prestart script on Windows:

> npm start -s
> yarn install v0.24.5
> [1/4] Resolving packages...
> success Already up-to-date.
> Done in 0.89s.
> 'node_modules' is not recognized as an internal or external command,
> operable program or batch file.

The prestart script runs just fine if its changed to
 `bower i && yarn && babel-node tools/bower`

Would removing the 'node_module/.bin/' path cause problems?

Others reference removing the full path in scripts with multiple commands: https://github.com/npm/npm/issues/4040

**Comment by philopian** [comment]
this should be fixed now!
